### ISSUE TITLE
problem with install

### ISSUE THREAD

**Issue by alexander-macleod** [linnovate/openideal#117]
I'm having
![Screenshot 2020-03-24 at 11 50 37 AM](https://user-images.githubusercontent.com/6178165/77423299-d6a04000-6dc6-11ea-9a00-53891b88f1f1.png)
 a problem with the install.

it gets to the first install screen ("let's go"), then it spits out the following error:

An AJAX HTTP error occurred. HTTP Result Code: 200 Debugging information follows. Path: http://[xxxxxxx]/install.php?profile=idea&locale=en&welcome=done&id=1&op=do StatusText: OK ResponseText: Fatal error: Declaration of RulesRuleUI::form(&$form, &$form_state, $options = Array) must be compatible with RulesActionContainerUI::form(&$form, &$form_state, $options = Array, $iterator = NULL) in [xxxxxxxx]/profiles/idea/modules/contrib/rules/ui/ui.plugins.inc on line 0

I initially thought it may be an execution time or a memory limit issue so i ramped up these in the ini and the .htaccess when the ini didn't work.

from what i have read online it may be an issue with the PHP version but I cannot find any docs here about what the recommended version of PHP is for the system.

Can someone enlighten me? I have tried 7.2.9 and 7.3.x - no dice with either.

The strange thing is that it tries to run the site but only manage a drupal boilerplate website with errors)

**Comment by Artmir** [comment]
The issue is with PHP7.x. Use Php 5.6 you will have no problems. Then you can upgrade your php after the install if you wish. Word of caution site will not have significant errors if you upgrade, but if you check the logs it will throw some errors that can potentially cause problems down the line. This is basically down to the issue how different php verisons store data. Hope this helps.
P.s. Change memory limits, caching and everything it asks. Take care to read all the exceptions it throws, they are all due to ini, httpd, etc settings. Do a quick google there are all answers you need what to change. During the installation you will get few exceptions with 5.6 but once you change everything it asks, it will install smoothly and you should have no problems. Been running this on one of my sites for over a year now without any issue. Only occasional division with 0 in challenegs. But that's another story.
